/**
 * stamp-version.mjs — record what this build is, for the About panel.
 *
 * The app has no build step: GitHub Pages serves the branch as it stands, so
 * nothing runs at deploy time that could stamp a commit into the files. And a
 * commit cannot contain its own hash. So this records what *is* knowable when
 * it runs: the version from `sw.js`, and the branch and commit the working tree
 * is built on top of. The panel says "built from" rather than naming it as this
 * build's own commit, because that is the true statement.
 *
 * Run it whenever CACHE_VERSION changes; CI fails if the two disagree.
 *
 *   node tools/stamp-version.mjs
 */

import { readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';

const ROOT = new URL('..', import.meta.url);
const OUT = new URL('assets/js/version.js', ROOT);

const git = (...args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();

const sw = await readFile(new URL('sw.js', ROOT), 'utf8');
const version = sw.match(/^const CACHE_VERSION = '([^']+)'/m)?.[1];
if (!version) throw new Error('sw.js has no CACHE_VERSION to read');

/**
 * The *published* branch this build's base sits on, not the working branch.
 * Work happens on a throwaway branch that is squashed into `main` and deleted,
 * so recording the local name would put a branch nobody can look up into the
 * panel of every deployed build. When the base is not on a remote branch yet —
 * a local commit, a fork — the working branch is the only true answer, so that
 * is what it falls back to.
 */
function branchOf() {
  const remote = git('branch', '--remotes', '--contains', 'HEAD')
    .split('\n')
    .map((line) => line.trim().replace(/^origin\//, ''))
    .filter((name) => name && !name.includes('->'));
  if (remote.includes('main')) return 'main';
  return remote[0] || git('rev-parse', '--abbrev-ref', 'HEAD');
}

const branch = branchOf();
const commit = git('rev-parse', '--short', 'HEAD');
const date = git('log', '-1', '--format=%ad', '--date=short');

const file = `/**
 * version.js — GENERATED by \`npm run stamp\`. Do not edit by hand.
 *
 * \`commit\` is the commit this build sits on top of, not the commit that
 * contains this file: a commit cannot carry its own hash, and with no build
 * step there is nothing at deploy time to fill one in. The About panel says
 * "built from" for exactly that reason. Every released version's own commit is
 * in the changelog beside it, where it is known.
 */

export const BUILD = Object.freeze({
  version: '${version}',
  branch: '${branch}',
  commit: '${commit}',
  date: '${date}',
});
`;

await writeFile(OUT, file, 'utf8');
console.log(`stamped ${version} · ${branch} · ${commit} · ${date}`);
